dist:
  name: opentelemetry-collector-iceberg
  description: OpenTelemetry Collector with Iceberg Exporter
  version: 0.142.0.1
  output_path: ./dist
  otelcol_version: 0.142.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.142.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.142.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.142.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.142.0
  - gomod: github.com/terakoya76/opentelemetry-iceberg-exporter v0.142.0.1
    name: icebergexporter
