dist:
  name: opentelemetry-collector-iceberg
  description: OpenTelemetry Collector with Iceberg Exporter
  version: 0.143.0.1
  output_path: ./dist
  otelcol_version: 0.143.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.143.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.143.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.143.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.143.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.143.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.143.0
  - gomod: github.com/terakoya76/opentelemetry-iceberg-exporter v0.143.0.1
    name: icebergexporter
  # - gomod: github.com/terakoya76/opentelemetry-iceberg-exporter v0.0.0
  #   name: icebergexporter

# replaces:
#   - github.com/terakoya76/opentelemetry-iceberg-exporter => ../
